/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.pacientes;

import modelo.Paciente;

/**
 * Vista de detalle de un paciente: encabezado con sus datos ({@link EncabezadoVistaPaciente})
 * arriba, y sus examenes ({@link DetalleExamenes}) abajo. Se abre como ventana flotante desde
 * el "ojito" de {@link TablaPacientes}.
 *
 * @author larre
 */
public class Vistadetallepaciente extends javax.swing.JPanel {

    private final EncabezadoVistaPaciente encabezado = new EncabezadoVistaPaciente();
    private final DetalleExamenes detalleExamenes = new DetalleExamenes();

    /**
     * Creates new form Vistadetallepaciente
     */
    public Vistadetallepaciente() {
        initComponents();

        setLayout(new java.awt.BorderLayout());
        add(encabezado, java.awt.BorderLayout.NORTH);
        add(detalleExamenes, java.awt.BorderLayout.CENTER);
    }

    /**
     * Carga los datos de un paciente: encabezado y examenes (ultimo + historial).
     */
    public void cargarPaciente(Paciente paciente) {
        encabezado.cargarDatosPaciente(paciente);
        detalleExamenes.cargarPaciente(paciente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
