/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 * Pantalla "Cambiar Contraseña".
 *
 * Sus componentes fueron creados en el editor visual de NetBeans a partir
 * de la pantalla de Login, reutilizando los componentes personalizados de
 * estilo del proyecto ({@link interfaz.PanelCurvo}, {@link
 * interfaz.JButtonRedondeado}, {@link interfaz.JPasswordFieldRedondeado}).
 *
 * Al copiarse desde Login también se copió, por error, la lógica de
 * autenticación del botón (consulta de credenciales, apertura de la
 * ventana principal, etc.), la cual fue retirada por no corresponder a
 * esta pantalla. Por el mismo motivo, el campo que originalmente recibía
 * el correo electrónico del login fue renombrado y pasado a un campo de
 * contraseña, ya que en esta pantalla corresponde a la nueva contraseña.
 *
 * Etapa actual: maquetado visual únicamente. El botón "Guardar Contraseña"
 * todavía no valida ni guarda datos, ya que esta pantalla no está
 * conectada a la base de datos.
 *
 * @author agust
 */
public class CambiarContraseña extends javax.swing.JPanel {

    /**
     * Se dispara cuando el usuario confirma una contraseña nueva (los dos
     * campos coinciden). Quien arme esta pantalla (por ejemplo
     * {@link RecuperarContrasenaFrame}) se suscribe para persistirla vía
     * {@link controlador.PasswordController#cambiarPassword}.
     */
    public interface ContrasenaGuardadaListener {
        void onContrasenaElegida(String nuevaPassword);
    }

    private final java.util.List<ContrasenaGuardadaListener> listenersGuardado = new java.util.ArrayList<>();

    public void addContrasenaGuardadaListener(ContrasenaGuardadaListener listener) {
        listenersGuardado.add(listener);
    }

    /**
     * Creates new form CambiarContraseña
     */
    public CambiarContraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 =  new interfaz.PanelCurvo();
        txtConfirmarContrasena = new interfaz.JPasswordFieldRedondeado();
        txtNuevaContrasena = new interfaz.JPasswordFieldRedondeado();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new interfaz.JButtonRedondeado();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        txtConfirmarContrasena.setBackground(new java.awt.Color(180, 195, 185));
        txtConfirmarContrasena.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        txtNuevaContrasena.setBackground(new java.awt.Color(180, 195, 185));
        txtNuevaContrasena.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(180, 200, 190));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(180, 195, 190));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nueva Contraseña");

        jLabel2.setBackground(new java.awt.Color(180, 200, 190));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(180, 195, 190));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Confirmar Contraseña");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nueva Contraseña");

        jLabel4.setBackground(new java.awt.Color(140, 165, 150));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(180, 195, 190));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Elegí una contraseña segura");

        jButton1.setText("Guardar Contraseña");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(140, 165, 150));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(180, 195, 190));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("para proteger tu cuenta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(txtConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Valida que las dos casillas coincidan acá mismo (es una regla de
        // la Vista, no de negocio); el largo mínimo y el guardado en la
        // base los valida controlador.PasswordController, a través de
        // quien esté escuchando ContrasenaGuardadaListener.
        char[] nueva = txtNuevaContrasena.getPassword();
        char[] confirmar = txtConfirmarContrasena.getPassword();

        if (nueva.length == 0 || confirmar.length == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Completá los dos campos de contraseña.",
                    "Faltan datos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!java.util.Arrays.equals(nueva, confirmar)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Las contraseñas no coinciden.",
                    "Contraseñas distintas", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nuevaPassword = new String(nueva);
        for (ContrasenaGuardadaListener listener : listenersGuardado) {
            listener.onContrasenaElegida(nuevaPassword);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtConfirmarContrasena;
    private javax.swing.JPasswordField txtNuevaContrasena;
    // End of variables declaration//GEN-END:variables
}
