package formulariosPrincipales;

/**
 * Pantalla de gestión de pacientes: lista los pacientes cargados en
 * {@code tablaPacientes1} y permite acotarlos con el buscador
 * {@code busqueda1}, filtrando por DNI o por Apellido y Nombre.
 */
public class Pacientes extends javax.swing.JPanel {

    /**
     * Arma la pantalla y conecta el buscador con la tabla: cada búsqueda
     * (tecleo o Enter) filtra por DNI o por Apellido y Nombre sobre los
     * pacientes ya cargados en {@code tablaPacientes1}.
     */
    public Pacientes() {
        initComponents();

        // Conecta el buscador de arriba con la tabla: cada vez que se
        // escribe (o se presiona Enter), se filtra por DNI o Apellido y
        // Nombre sobre los pacientes ya cargados.
        busqueda1.addBusquedaListener(new panels.Busqueda.BusquedaListener() {
            @Override
            public void onBuscar(String texto) {
                tablaPacientes1.filtrar(texto);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new panels.PanelBorder();
        tablaPacientes1 = new pacientes.TablaPacientes();
        busqueda1 = new panels.Busqueda();

        setPreferredSize(new java.awt.Dimension(982, 803));

        panelBorder1.setPreferredSize(new java.awt.Dimension(982, 803));

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablaPacientes1, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(tablaPacientes1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panels.Busqueda busqueda1;
    private panels.PanelBorder panelBorder1;
    private pacientes.TablaPacientes tablaPacientes1;
    // End of variables declaration//GEN-END:variables
}
