package formulariosPrincipales;

/**
 * Pantalla para elegir, de las órdenes pendientes o en proceso, cuál
 * pasar a cargar resultados. Lista esas órdenes en {@code tablaRegistros1}
 * (filtradas y ordenadas especialmente para este uso, ver constructor) y,
 * cuando el usuario elige una y confirma con "Siguiente", avisa mediante
 * {@link OrdenParaResultadosListener} a quien construyó la pantalla
 * (normalmente {@code Principal}) qué paciente y qué orden se
 * seleccionaron, para que se abra la pantalla de carga de resultados
 * correspondiente.
 */
public class RegistrarResultados extends javax.swing.JPanel {

    /**
     * Se dispara cuando el usuario elige una orden de la lista y confirma
     * con "Siguiente". Quien construye esta pantalla (Principal) se
     * suscribe para saber cuándo y con qué paciente/orden pasar a la
     * pantalla de carga de resultados.
     */
    public interface OrdenParaResultadosListener {
        void onOrdenSeleccionada(modelo.Paciente paciente, modelo.OrdenResumen orden);
    }

    private final java.util.List<OrdenParaResultadosListener> listenersOrden = new java.util.ArrayList<>();

    public void addOrdenParaResultadosListener(OrdenParaResultadosListener listener) {
        listenersOrden.add(listener);
    }

    /**
     * Arma la pantalla: configura {@code tablaRegistros1} para mostrar
     * solo lo pendiente de resultados (ver comentario debajo), conecta el
     * buscador con el filtro de la tabla, y agrega el manejador de
     * "Siguiente" que busca al paciente de la orden elegida y notifica a
     * los {@link OrdenParaResultadosListener} suscriptos.
     */
    public RegistrarResultados() {
        initComponents();

        // Esta pantalla es para trabajar sobre lo pendiente: a diferencia
        // de Registros (que muestra todo), acá la tabla solo debe traer
        // las órdenes con estado pendiente, en proceso o urgente (urgentes
        // primero), sin la columna Accion (no se usa acá) y con selección
        // de una sola orden por vez.
        tablaRegistros1.configurarParaRegistrarResultados();

        // Buscador (igual que en Registros): cada tecleo filtra la tabla
        // ya cargada, sin volver a consultar la base.
        busqueda1.addBusquedaListener(new panels.Busqueda.BusquedaListener() {
            @Override
            public void onBuscar(String texto) {
                tablaRegistros1.filtrar(texto);
            }
        });

        // "Siguiente": busca al paciente de la orden elegida y avisa a
        // quien esté escuchando (Principal) para que pase a la pantalla de
        // carga de resultados con esos datos ya cargados.
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelo.OrdenResumen orden = tablaRegistros1.getOrdenSeleccionada();
                if (orden == null) {
                    javax.swing.JOptionPane.showMessageDialog(RegistrarResultados.this,
                            "Seleccioná una orden de la lista antes de continuar.",
                            "Ninguna orden seleccionada", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }

                // Si buscarPorDni() devuelve null es casi siempre porque no
                // se pudo conectar (ConexionUtil ya mostró ese cartel): dado
                // que orden.getDni() sale de una orden real (con FK a
                // pacientes), un DNI sin paciente asociado sería un problema
                // de integridad de datos, no un caso esperable. En cualquiera
                // de los dos casos no hay nada más para hacer que frenar acá.
                modelo.Paciente paciente = controlador.PacienteController.buscarPorDni(
                        RegistrarResultados.this, orden.getDni());

                if (paciente == null) {
                    return;
                }

                for (OrdenParaResultadosListener listener : listenersOrden) {
                    listener.onOrdenSeleccionada(paciente, orden);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new panels.PanelBorder();
        busqueda1 = new panels.Busqueda();
        tablaRegistros1 = new registros.TablaRegistros();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(982, 803));

        panelBorder1.setPreferredSize(new java.awt.Dimension(982, 803));

        jButton2.setText("Siguiente");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(tablaRegistros1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(tablaRegistros1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panels.Busqueda busqueda1;
    private javax.swing.JButton jButton2;
    private panels.PanelBorder panelBorder1;
    private registros.TablaRegistros tablaRegistros1;
    // End of variables declaration//GEN-END:variables
}
