package acciones;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Panel con los 3 botones redondos (ver / editar / eliminar) que se pinta
 * dentro de la columna "Accion" de una tabla. Se usa junto con
 * {@link TableActionCellRender} (para dibujarlo en cada fila) y
 * {@link TableActionCellEditor} (para que los clics realmente funcionen -
 * en un JTable, una celda "clickeable" tiene que ser editable, si no los
 * botones se ven pero no reaccionan al mouse).
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Construye el panel e inicializa los 3 botones (ver/editar/eliminar)
     * con sus íconos, vía {@link #initComponents()}. Los listeners de cada
     * botón se conectan aparte, en {@link #initEvent(TableActionEvent, int)},
     * porque recién ahí se sabe a qué fila de la tabla corresponde el panel.
     */
    public PanelAction() {
        initComponents();
    }

    /**
     * Conecta cada botón con su acción correspondiente para la fila dada.
     */
    public void initEvent(TableActionEvent event, int row) {
        cmdView.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onView(row);
            }
        });
        cmdEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onEdit(row);
            }
        });
        cmdDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDelete(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdView = new acciones.ActionButton();
        cmdEdit = new acciones.ActionButton();
        cmdDelete = new acciones.ActionButton();

        cmdView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ojo.png"))); // NOI18N

        cmdEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lapiz.png"))); // NOI18N

        cmdDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/basura.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cmdView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cmdDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmdView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(cmdEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private acciones.ActionButton cmdDelete;
    private acciones.ActionButton cmdEdit;
    private acciones.ActionButton cmdView;
    // End of variables declaration//GEN-END:variables
}
